const String logoWithText = "assets/images/logo-no-background.png";
const String welcomeScreenUndraw = "assets/images/logo-no-background.png";
const String loginScreenUndraw = "assets/images/logo-no-background.png";

// SDG CARD PACK 1
const String sdgCafeteria = "assets/images/sdg_1_2_3.jpg";
const String sdgWaterPlant = "assets/images/sdg_1_6_8_9.jpg";
const String sdgWashingHands = "assets/images/sdg_1_6.jpg";
const String sdgHouse = "assets/images/sdg_1_11.jpg";
const String sdgSkyscraper = "assets/images/sdg_2_8.jpg";
const String sdgSharingFood = "assets/images/sdg_2_17.jpg";
const String sdgTreadmill = "assets/images/sdg_3_7.jpg";
const String sdgBike = "assets/images/sdg_3_11_12.jpg";
const String sdgFlood = "assets/images/sdg_3_13_14_15.jpg";
const String sdgSolar = "assets/images/sdg_4_5_7.jpg";
const String sdgClassroom = "assets/images/sdg_4_10_17.jpg";
const String sdgHospital = "assets/images/sdg_4_10.jpg";
const String sdgScience = "assets/images/sdg_5_8_9.jpg";
const String sdgWindTurbine = "assets/images/sdg_7_11.jpg";
const String sdgRoboticLegs = "assets/images/sdg_9_10.jpg";
const String sdgWheelchairs = "assets/images/sdg_10_17.jpg";
const String sdgProtest = "assets/images/sdg_12_13_17.jpg";
const String sdgPlantingTree = "assets/images/sdg_13_15_17.jpg";
const String sdgLandWater = "assets/images/sdg_14_15_17.jpg";
const String sdgUnderwaterJudge = "assets/images/sdg_14_16.jpg";
const String sdgReligiousTeamwork = "assets/images/sdg_16_17.jpg";
